=head1 DESCRIPTION

全部のキャリアで変換可能な絵文字の一覧です。

=head1 TABLE

    1 晴れ
    2 曇り
    3 雨
    4 雪
    5 雷
    6 台風
    8 小雨
    9 牡羊座
    10 牡牛座
    11 双子座
    12 蟹座
    13 獅子座
    14 乙女座
    15 天秤座
    16 蠍座
    17 射手座
    18 山羊座
    19 水瓶座
    20 魚座
    22 野球
    23 ゴルフ
    24 テニス
    25 サッカー
    26 スキー
    27 バスケットボール
    28 モータースポーツ
    30 電車
    31 地下鉄
    32 新幹線
    33 車（セダン）
    34 車（ＲＶ）
    35 バス
    36 船
    37 飛行機
    38 家
    39 ビル
    40 郵便局
    41 病院
    42 銀行
    43 ＡＴＭ
    44 ホテル
    45 コンビニ
    46 ガソリンスタンド
    47 駐車場
    48 信号
    49 トイレ
    50 レストラン
    51 喫茶店
    52 バー
    53 ビール
    54 ファーストフード
    55 ブティック
    56 美容院
    57 カラオケ
    58 映画
    59 右斜め上
    61 音楽
    62 アート
    63 演劇
    65 チケット
    66 喫煙
    67 禁煙
    68 カメラ
    69 カバン
    70 本
    71 リボン
    72 プレゼント
    73 バースデー
    74 電話
    75 携帯電話
    76 メモ
    77 ＴＶ
    79 ＣＤ
    80 ハート
    81 スペード
    82 ダイヤ
    83 クラブ
    84 目
    85 耳
    86 手（グー）
    87 手（チョキ）
    88 手（パー）
    89 右斜め下
    90 左斜め上
    91 足
    92 くつ
    94 車椅子
    96 やや欠け月
    97 半月
    98 三日月
    100 犬
    101 猫
    102 リゾート
    103 クリスマス
    104 左斜め下
    105 phone to
    106 mail to
    107 fax to
    110 メール
    115 ID
    116 パスワード
    119 サーチ（調べる）
    120 ＮＥＷ
    123 シャープダイヤル
    125 1
    126 2
    127 3
    128 4
    129 5
    130 6
    131 7
    132 8
    133 9
    134 0
    135 決定
    136 黒ハート
    137 揺れるハート
    138 失恋
    139 ハートたち（複数ハート）
    140 わーい（嬉しい顔）
    141 ちっ（怒った顔）
    142 がく〜（落胆した顔）
    143 もうやだ〜（悲しい顔）
    144 ふらふら
    145 グッド（上向き矢印）
    146 るんるん
    147 いい気分（温泉）
    149 キスマーク
    150 ぴかぴか（新しい）
    151 ひらめき
    152 むかっ（怒り）
    153 パンチ
    154 爆弾
    155 ムード
    156 バッド（下向き矢印）
    157 眠い(睡眠)
    158 exclamation
    162 あせあせ（飛び散る汗）
    163 たらーっ（汗）
    164 ダッシュ（走り出すさま）
    167 カチンコ
    172 夜
    176 時計
    1003 Tシャツ（ボーダー）
    1005 化粧
    1008 チャペル
    1010 ドル袋
    1011 パソコン
    1012 ラブレター
    1014 鉛筆
    1015 王冠
    1016 指輪
    1018 自転車
    1019 湯のみ
    1021 考えてる顔
    1022 ほっとした顔
    1023 冷や汗
    1024 冷や汗2
    1025 ぷっくっくな顔
    1026 ボケーっとした顔
    1027 目がハート
    1028 指でOK
    1029 あっかんべー
    1030 ウィンク
    1031 うれしい顔
    1032 がまん顔
    1033 猫2
    1034 泣き顔
    1035 涙
    1038 コピーライト
    1039 トレードマーク
    1040 走る人
    1041 マル秘
    1043 レジスタードトレードマーク
    1044 危険・警告
    1046 空室・空席・空車
    1048 満室・満席・満車
    1051 学校
    1052 波
    1053 富士山
    1054 クローバー
    1056 チューリップ
    1058 りんご
    1059 芽
    1060 もみじ
    1061 桜
    1062 おにぎり
    1063 ショートケーキ
    1064 とっくり（おちょこ付き）
    1065 どんぶり
    1066 パン
    1068 ひよこ
    1069 ペンギン
    1070 魚
    1071 うまい！
    1072 ウッシッシ
    1073 ウマ
    1074 ブタ
    1075 ワイングラス
    1076 げっそり
